version: 2
jobs:
  build:
    macos:
      xcode: "12.0.0"

    steps:
      - checkout

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_PROJECT: FBTweak.xcodeproj
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: FBTweak

      - store_test_results:
          path: test_output
 
      - store_artifacts:
          path: test_output
      
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
